// @generated
// This file is @generated by prost-build.
/// ============================================================================
/// 顶层输出：一个区块内所有 Swap 事件 (扁平化列表)
/// ============================================================================
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapEvents {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<SwapEvent>,
}
/// ============================================================================
/// 单条 Swap 事件 - 用于 K 线聚合
/// 设计参考: GMGN / DEXScreener 数据格式
/// ============================================================================
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapEvent {
    /// ========== 定位字段 ==========
    ///
    /// 流动性池地址 (Base58)
    #[prost(string, tag="1")]
    pub pool: ::prost::alloc::string::String,
    /// 交易签名 (Base58)
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    /// 交易发起者/Signer (Base58)
    #[prost(string, tag="3")]
    pub user: ::prost::alloc::string::String,
    /// ========== 平台与时间 ==========
    ///
    /// 平台标识: "meteora_dlmm" / "meteora_damm" / "meteora_dbc"
    #[prost(string, tag="4")]
    pub platform: ::prost::alloc::string::String,
    /// 毫秒级时间戳
    #[prost(uint64, tag="5")]
    pub timestamp_ms: u64,
    /// 区块高度
    #[prost(uint64, tag="6")]
    pub slot: u64,
    /// 交易在区块中的序号
    #[prost(uint32, tag="7")]
    pub tx_index: u32,
    /// ========== 交易对 ==========
    ///
    /// Base Token Mint (通常是 meme/项目币)
    #[prost(string, tag="8")]
    pub base_mint: ::prost::alloc::string::String,
    /// Quote Token Mint (通常是 SOL/USDC)
    #[prost(string, tag="9")]
    pub quote_mint: ::prost::alloc::string::String,
    /// ========== 金额 (原始精度, 无小数) ==========
    ///
    /// Base Token 数量
    #[prost(uint64, tag="10")]
    pub base_amount: u64,
    /// Quote Token 数量
    #[prost(uint64, tag="11")]
    pub quote_amount: u64,
    /// ========== 方向 ==========
    ///
    /// buy = 用 quote 买 base, sell = 卖 base 换 quote
    #[prost(enumeration="SwapSide", tag="12")]
    pub side: i32,
    /// ========== 精度 (可选, 方便前端展示) ==========
    ///
    /// Base Token 精度
    #[prost(uint32, tag="13")]
    pub base_decimals: u32,
    /// Quote Token 精度
    #[prost(uint32, tag="14")]
    pub quote_decimals: u32,
}
/// ============================================================================
/// 交易方向
/// ============================================================================
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SwapSide {
    SideUnknown = 0,
    /// 买入 Base (用 Quote 换 Base)
    SideBuy = 1,
    /// 卖出 Base (用 Base 换 Quote)
    SideSell = 2,
}
impl SwapSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SwapSide::SideUnknown => "SIDE_UNKNOWN",
            SwapSide::SideBuy => "SIDE_BUY",
            SwapSide::SideSell => "SIDE_SELL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIDE_UNKNOWN" => Some(Self::SideUnknown),
            "SIDE_BUY" => Some(Self::SideBuy),
            "SIDE_SELL" => Some(Self::SideSell),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
